### ISSUE TITLE
Small problem with some font descenders

### ISSUE THREAD

**Issue by daviddelmonte** [cbpowell/MarqueeLabel#38] opened 2013-10-18 20:10 UTC
Hi, first, thanks for a terrific control.

I find that it cuts off some font descenders (Futura for example). These are not custom fonts, in that they are part of iOS.. Maybe it's a system problem. But I thought you should be advised. 

I have seen this post describing a similar problem with custom fonts:

http://www.andyyardley.com/2012/04/24/custom-ios-fonts-and-how-to-fix-the-vertical-position-problem/

If there is a workaround, please let me know.

**Comment by simonbromberg** [comment] 2017-05-01 19:48
My UILabel is big enough to avoid this descender problem when I don't use MarqueeLabel, but when I do use it the letters get cut off (e.g. g) whenever the label is labelized (i.e. if it's animating the marquee the letters are not cut off). Even if I make the UILabel way bigger than necessary, after labelizing the letters get cut off.

Using FuturaStd-Medium

**Comment by cbpowell** [comment] 2017-05-02 02:45
@simonbromberg Hmm I just tried it in the demo project, changed the font of the first label to Futura Medium in IB and (probably) oversized the label, and didn't see the issue - could you be more specific on the configuration and/or set up a test case?

Side note - what do you mean by AutoLayout and not working because of MarqueeLabel?

**Comment by simonbromberg** [comment] 2017-05-04 14:13
I am not using the built in Futura Medium font but rather a custom one (although I have seen this kind of issue with built-in fonts before).

Re: side note As I mentioned, when the MarqueeLabel is animating, the letters are not cut-off, but when it labelizes it cuts off the letters. I suspect this is because the UILabel it uses internally is sizes using sizeToFit which can trump the constraints in IB.

**Comment by cbpowell** [comment] 2017-05-05 02:27
Well MarqueeLabel actually uses size**That**Fits, not sizeToFit, which doesn't inherently resize the view upon the call to that function. But that's probably irrelevant, because it does "manually" resize the sublabel frame to be equal to it's own `bounds.size.height` ([here](https://github.com/cbpowell/MarqueeLabel/blob/27f62dcc082ee10d154db2c4bfb3fef7ea55805f/Sources/Swift/MarqueeLabel.swift#L562) when labelized, and [here](https://github.com/cbpowell/MarqueeLabel/blob/27f62dcc082ee10d154db2c4bfb3fef7ea55805f/Sources/Swift/MarqueeLabel.swift#L588) when scrolling continuously).

However, I did just notice that the `LeftRight` type uses the [height from `expectedLabelSize`](https://github.com/cbpowell/MarqueeLabel/blob/27f62dcc082ee10d154db2c4bfb3fef7ea55805f/Sources/Swift/MarqueeLabel.swift#L616) rather than MarqueeLabel's own `bounds` like the other types (both in Swift and Objective-C versions).

Do you happen to be using the `LeftRight` type? I tried again with the demo project and a `LeftRight` type and didn't see the issue, but I'm still just using the regular Futura font.

**Comment by simonbromberg** [comment] 2017-05-05 04:21
Is `LeftRight` scrolling horizontally from left to right? If so, yes.

**Comment by cbpowell** [comment] 2017-05-05 19:26
If you use MarqueeLabel in such a way that it's easy to modify the code quickly, you could try changing [this line](https://github.com/cbpowell/MarqueeLabel/blob/27f62dcc082ee10d154db2c4bfb3fef7ea55805f/Sources/Swift/MarqueeLabel.swift#L616) to:
````swift
homeLabelFrame = CGRect(x: leadingBuffer, y: 0.0, width: expectedLabelSize.width, height: bounds.size.height).integral
````

Or for Objective-C, [this line](https://github.com/cbpowell/MarqueeLabel/blob/27f62dcc082ee10d154db2c4bfb3fef7ea55805f/Sources/ObjC/MarqueeLabel.m#L412) to:
````objc
self.homeLabelFrame = CGRectIntegral(CGRectMake(self.leadingBuffer, 0.0f, expectedLabelSize.width, self.bounds.size.height));
````

Or alternatively/more easily, temporarily change your label's `MarqueeType` to a continuous type and see if the problem goes away? The `leftRight` type is the only one that (incorrectly) uses the expectedLabelSize height rather than it's own bounds height. I'll fix that in an update soon too.

**Comment by cbpowell** [comment] 2017-05-06 16:02
I've pushed [release 3.0.5](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.0.5) - let me know if it fixes the issue for you!

**Comment by cbpowell** [comment] 2017-06-08 01:34
@simonbromberg did you get a chance to test the latest release? I'm thinking it probably corrected the issue.

**Comment by simonbromberg** [comment] 2017-06-08 01:51
I wound up modifying the descender/ascender of the font a bit. I'll have to go back into the commit history and test it from there when I get a chance.

**Comment by cbpowell** [comment] 2017-07-16 23:36
I'm thinking my change may have fixed it, so I'm going to (re)close this issue, but if you do check it and find the problem is still there please post again and I'll reopen!

**Closed by cbpowell** 2017-07-16 23:36 UTC
