### ISSUE TITLE
Can not build MarqueeLabel using Carthage

### ISSUE THREAD

**Issue by SlashPiggie** [cbpowell/MarqueeLabel#136] opened 2016-04-28 14:15 UTC
When I try to use 'carthage bootstrap', it returns this error

~ ~ ~
A shell task (/usr/bin/xcrun xcodebuild -project /Users/nammeo/Desktop/github/Media App/Carthage/Checkouts/MarqueeLabel/MarqueeLabelDemo/MarqueeLabelDemo.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'MarqueeLabelDemo.xcodeproj' from folder '/Users/nammeo/Desktop/github/Media App/Carthage/Checkouts/MarqueeLabel/MarqueeLabelDemo'.
	Reason: Project /Users/nammeo/Desktop/github/Media App/Carthage/Checkouts/MarqueeLabel/MarqueeLabelDemo/MarqueeLabelDemo.xcodeproj cannot be opened because it is missing its project.pbxproj file.
~ ~ ~

I don't want to use CocoaPods, I tried to install it manually by adding the swift to my project but I have no idea how to import the framework to my code.

Please help, thanks

**Comment by cbpowell** [comment] 2016-04-28 17:10
I'll check out the Carthage stuff later, in the interim you can always just add the MarqueeLabel.swift file to your project just like any other Swift file. Carthage builds a framework by design, but MarqueeLabel is really just a single Swift file.

**Comment by cbpowell** [comment] 2016-04-28 22:31
Should be fixed now! I reorganized the Sources directory awhile ago and forgot to update the MarqueeLabelTV target, apparently.

**Closed** 2016-04-28 22:30 UTC
Labels: Package Management

**Comment by SlashPiggie** [comment] 2016-04-28 23:00
Thank you for the fix

**Comment by Tchuba** [comment] 2019-07-02 15:50
This happened to me just now with the 4.0 release
